FROM --platform=linux/x86_64 ruby:3.3.5

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV RAILS_ENV=production

WORKDIR /myapp
COPY Gemfile Gemfile.lock /myapp/

RUN gem update --system
RUN bundle update --bundler

RUN bundle install

COPY . /myapp
RUN mkdir -p tmp/sockets
RUN mkdir -p tmp/pids

VOLUME /myapp/public
VOLUME /myapp/tmp

COPY entrypoint.prod.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.prod.sh
ENTRYPOINT ["entrypoint.prod.sh"]
EXPOSE 3000
