source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# レスポンスJSONを制御する
gem "active_model_serializers"

# エラーメッセージの日本語化
gem "rails-i18n"

gem "bootsnap", require: false

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[windows jruby]

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

gem 'deepl-rb', require: 'deepl'

# paginationのため
gem 'kaminari'

gem "algoliasearch-rails"

gem "devise"

gem "devise-i18n"

gem "devise_token_auth"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false
  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false

  # pryに関するgem
  # ruby3.5.0からostructが標準ライブラリではなくなったことでwarningが出ていた。明示的にgemfileに含める必要がある
  gem "ostruct"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # rubocopに関するgem
  gem "faker"
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
